{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0", "trace": "self = <case.test_api.TestApi object at 0x0000012520DF0748>, funcInfo = 1\n\n    def test_fail(self, funcInfo):\n        print(funcInfo)\n>       assert 1 == 0\nE       assert 1 == 0\n\ntest_api.py:152: AssertionError"}, "start": 1684058029022, "stop": 1684058029023, "uuid": "a4826b5e-ea2b-4cc8-8708-61f04cfb6525", "historyId": "357573bd99f54799b97d0ad69baff7b9", "testCaseId": "357573bd99f54799b97d0ad69baff7b9", "fullName": "case.test_api.TestApi#test_fail", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "V_PEARLHON-NBIO"}, {"name": "thread", "value": "19964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_api"}]}